{{- $v := $.Files.Get "fdbvalues.yaml" | fromYaml }}
{{- if $v.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "fullname" . }}-fdbserver
  labels:
    app: {{ template "fullname" . }}-fdbserver
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  podSelector:
    matchLabels:
      app: {{ template "fullname" . }}-fdbserver
      release: {{ .Release.Name }}
  ingress:
  - ports:
    - port: {{ $v.fdbserver.service.port }}
      protocol: TCP
{{- end }}
